resolver: lts-8.21
compiler: ghcjs-0.2.1.9008021_ghc-8.0.2
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9008021_ghc-8.0.2:
           url: https://github.com/achirkin/prepare-ghcjs/releases/download/lts-8.21-20170630/ghcjs-0.2.1.9008021_ghc-8.0.2.tar.gz
           sha1: 13d9bad7ba36c5ea5014afc2b815757ffef77a26

packages:
  - '.'
  - location:
      git: https://github.com/achirkin/easytensor.git
      commit: c51acab375ed7a194b9c1b87fdf151242406f001
    subdirs:
      - dimensions
      - easytensor
    extra-dep: true

extra-deps: []
flags: {}
